[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# Make so Ankh and Invis Joker combine both Square Jokers
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
G.jokers:emplace(card)
'''
position = 'after'
payload = '''
SQUARE_UP()
'''
match_indent = true